### ISSUE TITLE
1. faça um método que retorna a média de dados faltantes por coluna

### ISSUE THREAD

**Issue by felipexp8** [felipexp8/Avaliando_qualidade_dados_de_ocorrencia#1]

**Comment by felipexp8** [comment]
Primeiro item

**Comment by AMarcondes** [comment]
Criação da classe em andamento.
A classe irá:

- Carregar o arquivo CSV;

- Calcular a média de dados faltantes por campo;

- Retornar um dicionário com a média de dados faltantes por campo.

**Comment by AMarcondes** [comment]
Finalizada a atividade 1.

Caso algum erro ou problema seja encontrado, por favor informar.

**Comment by felipexp8** [comment]
Os dados estavam no _dataframe_ pandas, fiz um adaptador para funcionar no meu. 

Ele retorna os dados no modo ordinário `<list < list <str> >` (lista de lista de strings). Creio que seja útil caso não usem a automação do pandas nos itens 3 e 4

**Comment by AMarcondes** [comment]
Alterei o nome da classe que procura as células vazias.
