### ISSUE TITLE
2. Para cada item identifique até qual nível taxônomico a ocorrência foi identificada.

### ISSUE THREAD

**Issue by felipexp8** [felipexp8/Avaliando_qualidade_dados_de_ocorrencia#2]

**Comment by felipexp8** [comment]
Refazendo usando _numpy_. Detalhes no código

**Comment by felipexp8** [comment]
Refeito com o _numpy_

chamar apenas a função membro `AvaliaTax.verificaTaxonomiaAsNumpy(dados)`

formato de entrada:
`dados := list<list<str>> `
_lista de lista de String_

**Comment by felipexp8** [comment]
Preciso fazer o PandaAdapter...

**Comment by felipexp8** [comment]
> Preciso fazer o PandaAdapter...

_Pronto_. Exemplo:

```
csv_file = 'portalbio_export_17-10-2019-13-06-22.csv'  
csv_open = MyData(csv_file)   
mean_nan_values = csv_open.getEmpty()  

listagemXY = AvaliaTax.pandasAdapter(csv_open.df)
nivelTax = AvaliaTax.verificaTaxonomiaAsNumpy(listagemXY)
```

**Comment by wbbatista** [comment]
Felipe, poderias comentar em seu codigo o porque de usar @staticmethod e qual a funçao do mesmo?

**Comment by felipexp8** [comment]
> Felipe, poderias comentar em seu codigo o porque de usar @staticmethod e qual a funçao do mesmo?

Pronto, também coloquei no _readme.md_

**Comment by wbbatista** [comment]
você pode fechar a issue.
