### ISSUE TITLE
5. Teste da classe desenvolvida com os 3 arquivos passados

### ISSUE THREAD

**Issue by felipexp8** [felipexp8/Avaliando_qualidade_dados_de_ocorrencia#5]
5. Teste da classe desenvolvida com os 3 arquivos passados, os arquivos referem-se a diferentes regiões e quantidades, um deles é um pouco maior e talvez vocês tenham problemas de desempenho. Dessa forma, espera-se que seja avaliado os resultados a respeito de dados faltantes, preenchimento taxonômico, diferença entre lat e log para cada um dos arquivos, e que seja escrito uma discussão por grupo.

**Comment by AMarcondes** [comment]
Teste realizado em cada uma das classes, para os três arquivos.

Fiz no Jupyter Notebook e as quatro partes funcionaram perfeitamente.

**Comment by wbbatista** [comment]
blz
