### ISSUE TITLE
Caiu meu Whatsapp (vai por aqui)

### ISSUE THREAD

**Issue by felipexp8** [felipexp8/Avaliando_qualidade_dados_de_ocorrencia#9]
Meu _whatsapp_ está com problemas e não estou vencendo todo dia portar para o emulador, pois o conteúdo dos chats em grupos desaparece com frequência.

O wifi daqui requer autenticação via web e não por senha SKA, não consigo fazer rigorosamente a cada 30min o login na tela do celular, é muito chato.

**Comment by AMarcondes** [comment]
Tranquilo, Felipe. Podemos nos reunir no Zoom amanhã para finalizar isso.

**Comment by wbbatista** [comment]
Fechando  as issues
